#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

TERRAFORM_DIRECTORY=infrastructure/terraform

echo
echo "💡  if there are any errors, make sure to check SPECIFICALLY which check fails"
echo

# adopted from kentcdodds.com
npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "lint,check-types,prettier:ci,terraformValidate,terraformFormat" \
  \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white,bgCyan.bold.white" \
  "npm run lint --silent" \
  "npm run check-types --silent" \
  "npm run prettier:ci --silent -- --log-level silent" \
  "terraform -chdir=$TERRAFORM_DIRECTORY validate" \
  "terraform -chdir=$TERRAFORM_DIRECTORY fmt"
