#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# adopted from kentcdodds.com
npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "lint,typecheck,format" \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white" \
  "npm run lint --silent" \
  "npm run check-types --silent" \
  "npm run prettier --silent -- --loglevel silent"
