name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run CI and build in Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm' # @TODO look into this - https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      - run: npm ci
      - run: npm run prettier:ci
      - run: npm run build # build checks types and runs linter
  deploy-to-s3:
    runs-on: ubuntu-latest
    needs: ci-build

    steps:
      # https://github.com/aws-actions/configure-aws-credentials
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          # @TODO eventually switch to OIDC instead of IAM role?
      - run:
          aws sts get-caller-identity # test AWS credentials setup


          # Next run in this step: deploy using S3 CLI
# Next job: Invalidate Cloudfront
